version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/goreleaser/goreleaser
    versions:
    - 0.155.0
    - 0.155.1
    - 0.155.2
    - 0.156.1
    - 0.156.2
    - 0.157.0
    - 0.158.0
  - dependency-name: github.com/golangci/golangci-lint
    versions:
    - 1.36.0
    - 1.37.0
    - 1.37.1
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.1
    - 1.1.2
  - dependency-name: github.com/jarcoal/httpmock
    versions:
    - 1.0.7
