env:
  - CGO_ENABLED=0
before:
  hooks:
    - make test
builds:
  - id: "h7t"
    main: ./main.go
    binary: h7t
    ldflags:
     - -s -w -X github.com/damianoneill/h7t/cmd.version={{.Version}} -X github.com/damianoneill/h7t/cmd.commit={{.Commit}} -X github.com/damianoneill/h7t/cmd.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
  - id: "plugin-csv"
    main: ./plugins/csv/main.go
    binary: transformer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
dockers:
 - binaries:
     - h7t
     - transformer
   image_templates:
     - "docker.pkg.github.com/damianoneill/h7t:latest"
     - "docker.pkg.github.com/damianoneill/h7t:{{ .Tag }}"
   dockerfile: Dockerfile
archives:
  - replacements:
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
